# (PART) Finch Selection {-}

# Introduction

In this activity you will be introduced to scripts, graphing, and analysis in R. 

<div class="mx-auto" style="width: 320px;">
  <iframe width="320" height="446" src="https://macaulaylibrary.org/asset/83940941/embed/320" frameborder="0" allowfullscreen style="width:320px;"></iframe>
</div>

You will use the Finches dataset to learn how to read a tabular dataset into R, inspect it, and perform basic statistical summaries on it. You will estimate means, standard deviations, standard errors of the mean, and confidence intervals around the mean. You will also learn how to plot histograms and bar charts (also called column charts).

The question you are tasked with answering for Part 3 is:

<blockquote class="text-success">Did beak length vary between birds that survived the drought and those that did not?</blockquote>

## The finch dataset

In the finch dataset, each row represents an individual bird that was banded before the 1977 drought on Daphne Major island in the Galapagos archipelago. The variable named `outcome` contains one of two values: **survived** or **died**, depending on whether the bird was ever seen after the drought or not.
