# (PART) Intraspecific Variation {-}

# Intraspecific Variation

## Introduction

In this activity you will apply what you have learned in Finch Selection Example to the plant growth data you collected in the field during your Organismal Biology lab.

On your field trip to the MSUM Regional Science Center, you collected data to compare how Big Bluestem (*Andropogon gerardii*) plants allocate energy towards growth and reproduction. 

You measured the plant height as a proxy for growth and rame length as a proxy for reproduction.

You sampled plants at two sites: 

1. **Site A**, at the MSUM Regional Science Center, was last burned in spring 2018. The site was previously part of a golf course and was restored to grassland about 30 years ago. Your instructor may have called this the "unburned" site, but note that it has been burned in the past, just not recently.
2. **Site B**, at the Bluestem Prairie Scientific and Natural Area, was last burned in spring 2023. The site is remnant native grassland, meaning it has never been plowed. Your instructor may have called this the "burned" site.

Both sites are managed by the Minnesota Department of Natural Resources and The Nature Conservancy using a combination of fire, mowing, and chemical treatment to control invasive species.

You will compare the plant heights and rame lengths of plants in these two sites, using the same steps you used to compare finches that died vs. survived in the Finch Selection Example.

## The question

The goal of the activity is to answer the following question:

<blockquote class="text-success">Do plant height or rame length of Big Bluestem (<i>Andropogon gerardii</i>) plants vary between site A and site B?</blockquote>

## Your assignment

In this activity, you will create a new R script, read the grass data into R, plot histograms of plant height and rame length, estimate the means of those variables, plot them on bar charts, and compare the means using a *t*-test.

Then create a new Microsoft Word document, copy your figures into it, and write figure legends for them, and write a Results paragraph that cites the figures and the results from the *t*-test. Submit this document to your instructor.
